### PR TITLE
Fix errors: "list M1 not found " and "nonce too low"

### PR DESCRIPTION
**Pull request by gzliudan**
# About this PR

### 1.1 Symptom

- https://www.xdc.dev/poonam_singh_8d4036dd4427/setting-up-private-blockchain-network-118c
- https://www.xdc.dev/lucksin3/xdc-private-network-stuck-at-block-1799-with-error-failed-to-prepare-header-for-new-block-errlist-m1-not-found--7gc

### 1.2 Solution

This PR fix issue #228 by call function `contracts.CreateTransactionSign` at continuous block range [0, common.MergeSignRange) during each epoch. The block range is [0, 14] generally if common.MergeSignRange is default value 15.

### 2.1 Symptom

https://www.xdc.dev/raghuram/xdc-private-blockchain-fail-to-create-tx-sign-for-signer-error-5ck

### 2.2 Solution

Sometimes `pool.AddLocal(txSigned)` return error `ErrNonceTooLow` in function CreateTransactionSign when nonce conflicts. The log report error as below:

```
Fail to add tx sign to local pool. error="nonce too low"
```

If this error occurs, this PR will log a warn message and retry `pool.AddLocal(txSigned)` until reaches 10 times.

### CODE REVIEW

**Comment by raghu0891** [comment]
Team,

We got the ERROR "list M1 not found", when the block number was reaching 1800, which is twice the epoch value of 900 in the genesis file.

image

**Comment by gzliudan** [comment]
> Team,
> 
> We got the ERROR "list M1 not found", when the block number was reaching 1800, which is twice the epoch value of 900 in the genesis file.
> 
> image

@raghu0891 Would you please upload all nodes's log files? Or mail to me: 139250065@qq.com ?

**Comment by gzliudan** [comment]
@raghu0891  You mentioned that using 3 physical servers in email. So I created a new genesis file only include 1 master node (not signer role) and 2 signer node. Please refer:

- https://github.com/gzliudan/Local_DPoS_Setup/blob/private-network/setup-guide.md
- https://github.com/gzliudan/Local_DPoS_Setup/blob/private-network/genesis/XDPoS-2-signers.json
- https://github.com/gzliudan/Local_DPoS_Setup/blob/private-network/start-2-signers-networks.sh

The new private network passed 1800 blocks, but is stuck at block 2701, because both signer mined block 2701:

**signer 1**

```text
INFO [03-17|17:11:59] Receive future block                     number=2700 hash=0xdac32464e6056365fd5c731a078b51d6743bbcef593a0c4f00468d6f92cea140 delay=1.94784196s
INFO [03-17|17:12:01] Imported new chain segment               blocks=1 txs=1 mgas=0.025 elapsed=526.651µs mgasps=48.138  number=2700 hash=dac324…cea140                                                      cache=127.09kB
INFO [03-17|17:12:01] Checkpoint!!! It's time to reconcile node's state... 
INFO [03-17|17:12:01] Committing new block                     number=2701 txs=1 special-txs=1 uncles=0 elapsed=1.136ms
INFO [03-17|17:12:01] Successfully sealed new block            number=2701 hash=1a3941…518356
```

**signer 2**

```text
INFO [03-17|17:12:11] Not my turn to commit block. Waiting... 
INFO [03-17|17:12:11] Distance from the parent block           seconds=10 hops=1
INFO [03-17|17:12:11] Wait enough. It's my turn                waited seconds=10
INFO [03-17|17:12:11] Committing new block                     number=2701 txs=2 special-txs=1 uncles=0 elapsed=1.495ms
INFO [03-17|17:12:11] Signed recently, must wait for others    len(masternodes)=2 number=2701 limit=2 seen=2700 recent=xdc96509A56F0243b10a2706391b95af449712da699 snap.Recents="map[2699:[119 203 133 174 10 224 112 223 192 19 186 26 91 62 225 206 212 160 89 167] 2700:[150 80 154 86 240 36 59 16 162 112 99 145 185 90 244 73 113 45 166 153]]"
```

This is the case of brain split. So we should run 3 or 5 signers, do not configure 2 or 4 signers,

**Comment by gzliudan** [comment]
I run my script https://github.com/gzliudan/Local_DPoS_Setup/blob/private-network/start-2-signers-networks.sh for the second time. It passed 1800 block also. But it is not stuck at block 2701 now. If you still experience any problem, please send your instruction and log files to me.

**Comment by raghu0891** [comment]
@gzliudan Yes, the code from your Repo https://github.com/gzliudan/Local_DPoS_Setup/blob/private-network/ is helpful in starting the private node. Now the blocks in newly setup private node is steadily moving beyond 41000.

image

**Comment by gzliudan** [comment]
@nitishpatel Not find error from your screenshot. Could you please upload your log files?

**Comment by lucksin3** [comment]
This PR fixed the List M1 not found. have extensively tested this multiple times.

**Review by AnilChinchawale — APPROVED** [review]

**Comment by liam-lai** [comment]
In your PR description, why nonce `sometimes` conflicts? I think we need to fix this, not just keep retry.

**Comment by gzliudan** [comment]
I guess it is caused by special txs. Maybe this nonce error can be solved by PR #171.

> In your PR description, why nonce `sometimes` conflicts? I think we need to fix this, not just keep retry.

**Pull request closed without merging**
