### PR TITLE
Increase gas price from 250000000 to 12500000000

### PR DESCRIPTION
**Pull request by gzliudan**
# Proposed changes

This PR closes issue #288, change gas price from 250000000 to 12500000000. The new gas price will take effect from block number:

- devnet: 9757200, Fri Aug 25 2023 11:00:00 GMT+1200
- testnet(apothem): TIPTRC21Fee + 30000000 = 23779191 + 30000000 = 53779191
- mainnet(xinfin): TIPTRC21Fee + 30000000 = 38383838 + 30000000 = 68383838

## Types of changes

What types of changes does your code introduce to XDC network?

- [ ] Bugfix
- [✅] New feature
- [ ] Documentation Update or any other KTLO
- [ ] Not sure (Please specify below)

## Impacted Components

Which part of the codebase this PR will touch base on,

- [ ] Consensus
- [ ] Account
- [✅] Network
- [ ] Geth
- [ ] Smart Contract
- [ ] External components
- [ ] Not sure (Please specify below)

## Checklist

- [✅] This PR has sufficient test coverage (unit/integration test) OR I have provided reason in the PR description for not having test coverage
- [ ] Provide an end-to-end test plan in the PR description on how to manually test it on the devnet/testnet.
- [ ] Tested the backwards compatibility.
- [ ] Relevant documentation has been updated as part of this PR

## How to test manually

Run below tests before and after the time of taking effect.

#### 1. call method `eth_gasPrice`

Call the method `eth_gasPrice`, check the response:

```bash
curl -s -X POST -H "Content-Type: application/json" ${SERVER} -d '
{
  "jsonrpc": "2.0",
  "id": 1003,
  "method": "eth_gasPrice",
  "params": []
}' | jq
```

#### 2. deploy a smart contract

Deploy a smart contract by Remix and MetaMask, check gas price in MetaMask when confirm.

#### 3. execute a transaction

Execute a transaction in Remix, check gas price in MetaMask when confirm.

### CODE REVIEW

**Comment by wgr523** [comment]
May I ask what is the basis for setting block numbers? Shouldn't we do tests on devnet for some while, and then set the block numbers for testnet and mainnet?

> * devnet: 9757200, Fri Aug 25 2023 11:00:00 GMT+1200
> * testnet(apothem): TIPTRC21Fee + 30000000 = 23779191 + 30000000 = 53779191
> * mainnet(xinfin): TIPTRC21Fee + 30000000 = 38383838 + 30000000 = 68383838

**Review by AnilChinchawale — APPROVED** [review]

**Comment by liam-lai** [comment]
Please add  `BlockNumberGas50x` at this file also common/constants/constants.go.testnet

**Comment by gzliudan** [comment]
Done

**Comment by gzliudan** [comment]
> Please add `BlockNumberGas50x` at this file also common/constants/constants.go.testnet

Done

**Pull request merged**
