### PR TITLE
XDV-06 also update array length when deleting candidates and owners

### PR DESCRIPTION
**Pull request by wanwiset25**
# Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.

## Types of changes

What types of changes does your code introduce to XDC network?
_Put an `✅` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Regular KTLO or any of the maintaince work. e.g code style
- [ ] CICD Improvement

## Impacted Components
Which part of the codebase this PR will touch base on,

_Put an `✅` in the boxes that apply_

- [ ] Consensus
- [ ] Account
- [ ] Network
- [ ] Geth
- [ ] Smart Contract
- [ ] External components
- [ ] Not sure (Please specify below)

## Checklist
_Put an `✅` in the boxes once you have confirmed below actions (or provide reasons on not doing so) that_

- [ ] This PR has sufficient test coverage (unit/integration test) OR I have provided reason in the PR description for not having test coverage
- [ ] Provide an end-to-end test plan in the PR description on how to manually test it on the devnet/testnet.
- [ ] Tested the backwards compatibility.
- [ ] Tested with XDC nodes running this version co-exist with those running the previous version.
- [ ] Relevant documentation has been updated as part of this PR
- [ ] N/A

### CODE REVIEW

**Review by GalaxySciTech — CHANGES_REQUESTED** [review]
leave here , i will change the code

**Review by GalaxySciTech — COMMENTED** [review]
changed over

**Review by GalaxySciTech — APPROVED** [review]

**Comment by wjrjerome** [comment]
Please do NOT merge this PR for the time bing.
We will need to decide how we going to approach the sol changes first

**Comment by gzliudan** [comment]
Do not modify the contract code unless we can redeploy it.

**Comment by gzliudan** [comment]
The function `removeZeroAddresses` can be called before `break;` to save gas.

**Review by GalaxySciTech — COMMENTED** [review]
keep it

**Comment by GalaxySciTech** [comment]
> The function `removeZeroAddresses` can be called before `break` or after `delete` to save gas.

Cannot modify the number of arrays in a for loop. This is a serious bug.

**Comment by gzliudan** [comment]
> > The function `removeZeroAddresses` can be called before `break` or after `delete` to save gas.
> 
> Cannot modify the number of arrays in a for loop. This is a serious bug.

In fact, we can because we break the loop at once:

```solidity
        for (uint256 i = 0; i < candidates.length; i++) {
            if (candidates[i] == _candidate) {
                delete candidates[i];
                candidates = removeZeroAddresses(candidates);   
                break;
            }
        }
```

**Comment by GalaxySciTech** [comment]
> > > The function `removeZeroAddresses` can be called before `break` or after `delete` to save gas.
> > 
> > 
> > Cannot modify the number of arrays in a for loop. This is a serious bug.
> 
> In fact, we can because we break the loop at once:
> 
> ```solidity
>         for (uint256 i = 0; i < candidates.length; i++) {
>             if (candidates[i] == _candidate) {
>                 delete candidates[i];
>                 candidates = removeZeroAddresses(candidates);   
>                 break;
>             }
>         }
> ```



> > > The function `removeZeroAddresses` can be called before `break` or after `delete` to save gas.
> > 
> > 
> > Cannot modify the number of arrays in a for loop. This is a serious bug.
> 
> In fact, we can because we break the loop at once:
> 
> ```solidity
>         for (uint256 i = 0; i < candidates.length; i++) {
>             if (candidates[i] == _candidate) {
>                 delete candidates[i];
>                 candidates = removeZeroAddresses(candidates);   
>                 break;
>             }
>         }
> ```

yeah , you are right,because it breaked

but also break put it outside ,it is no saved gas

**Review by gzliudan — CHANGES_REQUESTED** [review]
```solidity
                    delete candidates[i];
                    delete validatorsState[candidates[i]];
```

should be changed to:

```solidity
                    delete validatorsState[candidates[i]];
                    delete candidates[i];
```

**Comment by gzliudan** [comment]
But it is unnecessary to call the function `removeZeroAddresses` if the loop is not break.

> yeah , you are right,because it breaked
> 
> but also break put it outside ,it is no saved gas
> 
> just make the code to be more standard.
> 
> Even if we remove break in the future, there will be no mistakes here.

**Comment by GalaxySciTech** [comment]
> removeZeroAddresses

it is necessary. , removeZeroAddresses will solve zero address issue

**Comment by gzliudan** [comment]
Yes, there are some zero gaps in current arrays now.

> > removeZeroAddresses
> 
> it is necessary. , removeZeroAddresses will solve zero address issue

**Comment by gzliudan** [comment]
BTW, we can get `allMasternodes` from `ownerToCandidate[_invalidMasternode]`. So 

```soldity
            address[] memory allMasternodes = new address[](candidates.length-1) ;
            uint count=0;
            for (uint i=0;i<candidates.length;i++){
                if (getCandidateOwner(candidates[i])==_invalidMasternode){
                    // logic to remove cap.
                    candidateCount = candidateCount.sub(1);
                    allMasternodes[count++] = candidates[i];
                    delete candidates[i];
                    delete validatorsState[candidates[i]];
                    delete KYCString[_invalidMasternode];
                    delete ownerToCandidate[_invalidMasternode];
                    delete invalidKYCCount[_invalidMasternode];
                }
            }
```

can be changed to

```soldity
            address[] memory allMasternodes = ownerToCandidate[_invalidMasternode];
            address[] memory arrayCache = candidates;
            uint256 arrayLength = arrayCache.length;
            for (uint i = 0; i < arrayLength; i++){
                if (getCandidateOwner(arrayCache[i]) == _invalidMasternode){
                    // logic to remove cap.
                    candidateCount = candidateCount.sub(1);
                    delete validatorsState[arrayCache[i]];
                    delete candidates[i];
                    delete KYCString[_invalidMasternode];
                    delete ownerToCandidate[_invalidMasternode];
                    delete invalidKYCCount[_invalidMasternode];
                }
            }
```

**Comment by GalaxySciTech** [comment]
> ```solidity
>                     delete candidates[i];
>                     delete validatorsState[candidates[i]];
> ```
> 
> should be changed to:
> 
> ```solidity
>                     delete validatorsState[candidates[i]];
>                     delete candidates[i];
> ```

what the reason we need change this

**Comment by gzliudan** [comment]
> > ```solidity
> >                     delete candidates[i];
> >                     delete validatorsState[candidates[i]];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > should be changed to:
> > ```solidity
> >                     delete validatorsState[candidates[i]];
> >                     delete candidates[i];
> > ```
> 
> what the reason we need change this

```solidity
                    delete candidates[i]; // candidates[i] is 0 after delete
                    delete validatorsState[candidates[i]]; // this line become delete validatorsState[0];
```

**Comment by GalaxySciTech** [comment]
> BTW, we can get `allMasternodes` from `ownerToCandidate[_invalidMasternode]`. So
> 
> ```
>             address[] memory allMasternodes = new address[](candidates.length-1) ;
>             uint count=0;
>             for (uint i=0;i<candidates.length;i++){
>                 if (getCandidateOwner(candidates[i])==_invalidMasternode){
>                     // logic to remove cap.
>                     candidateCount = candidateCount.sub(1);
>                     allMasternodes[count++] = candidates[i];
>                     delete candidates[i];
>                     delete validatorsState[candidates[i]];
>                     delete KYCString[_invalidMasternode];
>                     delete ownerToCandidate[_invalidMasternode];
>                     delete invalidKYCCount[_invalidMasternode];
>                 }
>             }
> ```
> 
> can be changed to
> 
> ```
>             address[] memory allMasternodes = ownerToCandidate[_invalidMasternode];
>             address[] memory arrayCache = candidates;
>             uint256 arrayLength = arrayCache.length;
>             for (uint256 i = 0; i < arrayLength; i++){
>                 if (getCandidateOwner(arrayCache[i]) == _invalidMasternode){
>                     // logic to remove cap.
>                     candidateCount = candidateCount.sub(1);
>                     delete validatorsState[arrayCache[i]];
>                     delete candidates[i];
>                     delete KYCString[_invalidMasternode];
>                     delete ownerToCandidate[_invalidMasternode];
>                     delete invalidKYCCount[_invalidMasternode];
>                 }
>             }
> ```

What are the benefits of doing this

**Comment by gzliudan** [comment]
> What are the benefits of doing this

- save gas by skip `allMasternodes[count++] = candidates[i];`
- fit `allMasternodes` to real size, not allocate useless memory for big array with many zero address at the tail

**Comment by wgr523** [comment]
> Do not modify the contract code unless we can redeploy it.

I agree

**Comment by GalaxySciTech** [comment]
close and make new one name call upgrade sc

**Pull request closed without merging**
